# @generated by PeggyGD __VERSION__.
extends JSParser
class_name __CLAZZ_NAME__

##GLOBALS##

##TABLES##

##EXPRESSIONS##

func parse(input: String, options = {})->PEG.Result:
##START_RULES##
  return super(input, options)
